# Generated by Django 3.1.14 on 2022-04-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220428_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='customerPhone',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='customerinfo',
            unique_together=set(),
        ),
    ]
