# Generated by Django 3.0.8 on 2022-04-28 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_customerinfo_walletmoney'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customerinfo',
            constraint=models.CheckConstraint(check=models.Q(registrationDate__lte=datetime.date(2022, 4, 29)), name='DateValidation'),
        ),
    ]
