# Generated by Django 3.1.14 on 2022-04-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_customerinfo_walletmoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creates',
            name='itemQty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='customerPhone',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='itemDescription',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='itemSize',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='outletID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='pincode',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='outletphone',
            name='phoneNo',
            field=models.PositiveIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='waiterID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='creates',
            constraint=models.CheckConstraint(check=models.Q(itemQty__gte=0), name='qtyvalidation'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(materialID__gt=0), name='id4validation'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(materialQty__gte=0), name='mqtyvalidation'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(threshQty__gt=0), name='tqtyvalidation'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(costPrice__gt=0), name='cpvalidation'),
        ),
        migrations.AddConstraint(
            model_name='itemdetails',
            constraint=models.CheckConstraint(check=models.Q(itemID__gt=0), name='id3validation'),
        ),
        migrations.AddConstraint(
            model_name='itemdetails',
            constraint=models.CheckConstraint(check=models.Q(itemPrice__gt=0), name='priceValidation'),
        ),
        migrations.AddConstraint(
            model_name='itemdetails',
            constraint=models.CheckConstraint(check=models.Q(itemSize__lte=2), name='sizeValidation'),
        ),
        migrations.AddConstraint(
            model_name='outlet',
            constraint=models.CheckConstraint(check=models.Q(outletID__gt=0), name='id1validation'),
        ),
        migrations.AddConstraint(
            model_name='outlet',
            constraint=models.CheckConstraint(check=models.Q(pincode__lte=999999), name='pincodeValidation'),
        ),
    ]
