# Generated by Django 3.1.14 on 2022-04-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220429_1434'),
        ('app', '0007_auto_20220429_0327'),
    ]

    operations = [
    ]
