# Generated by Django 3.1.14 on 2022-04-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20220429_1908'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='creates',
            name='qtyvalidation',
        ),
        migrations.RemoveConstraint(
            model_name='customerinfo',
            name='DateValidation',
        ),
        migrations.RemoveConstraint(
            model_name='inventory',
            name='id4validation',
        ),
        migrations.RemoveConstraint(
            model_name='inventory',
            name='mqtyvalidation',
        ),
        migrations.RemoveConstraint(
            model_name='inventory',
            name='tqtyvalidation',
        ),
        migrations.RemoveConstraint(
            model_name='inventory',
            name='cpvalidation',
        ),
        migrations.RemoveConstraint(
            model_name='itemdetails',
            name='id3validation',
        ),
        migrations.RemoveConstraint(
            model_name='itemdetails',
            name='priceValidation',
        ),
        migrations.RemoveConstraint(
            model_name='itemdetails',
            name='sizeValidation',
        ),
        migrations.RemoveConstraint(
            model_name='outlet',
            name='id1validation',
        ),
        migrations.RemoveConstraint(
            model_name='waiter',
            name='id2validation',
        ),
        migrations.AlterField(
            model_name='outletphone',
            name='phoneNo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='creates',
            constraint=models.CheckConstraint(check=models.Q(itemQty__gte=0), name='itemQtyValidation'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(materialID__gt=0), name='materialIDValidation'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(materialQty__gte=0), name='materialQtyValidation'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(threshQty__gt=0), name='threshQtyValidation'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(costPrice__gt=0), name='costPriceValidation'),
        ),
        migrations.AddConstraint(
            model_name='itemdetails',
            constraint=models.CheckConstraint(check=models.Q(itemID__gt=0), name='itemIDValidation'),
        ),
        migrations.AddConstraint(
            model_name='itemdetails',
            constraint=models.CheckConstraint(check=models.Q(itemPrice__gt=0), name='itemPriceValidation'),
        ),
        migrations.AddConstraint(
            model_name='itemdetails',
            constraint=models.CheckConstraint(check=models.Q(itemSize__lte=2), name='itemSizeValidation'),
        ),
        migrations.AddConstraint(
            model_name='outlet',
            constraint=models.CheckConstraint(check=models.Q(outletID__gt=0), name='outletIDvalidation'),
        ),
        migrations.AddConstraint(
            model_name='waiter',
            constraint=models.CheckConstraint(check=models.Q(waiterID__gt=0), name='waiterIDvalidation'),
        ),
    ]
